[project]
name = "python-ciso-assistant-client"
version = "0.1.0"
description = "A client library for accessing CISO Assistant API"
authors = [
    { name = "Johan Lundberg", email = "lundberg@sunet.se" }
]
readme = "README.md"
license = "BSD-2-Clause"
license-files = ["LICEN[CS]E*"]
requires-python = ">=3.11"
keywords = [
    "ciso-assistant",
    "api",
    "client",
    "http",
    "rest",
    "async",
    "httpx",
    "pydantic",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Typing :: Typed",
]
dependencies = [
    "httpx>=0.28.1",
    "pydantic>=2.12.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/ciso_assistant_client"]

[dependency-groups]
dev = [
    "pytest>=8.3.4",
    "pytest-asyncio>=0.25.2",
    "respx>=0.22.0",
]

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
